version: '3.4'
services:

  api:
    build: 
      context: .
      dockerfile: docker/api/dockerfile

    restart: always

    environment:
      - API_REDIS_HOST=redis

    ports:
      - 8000:8000
    
    command: [
      "poetry", "run", 
      "uvicorn", "app:create_app", 
      "--host", "0.0.0.0",
      "--port", "8000"
    ]

    depends_on:
      - redis

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: docker/redis/dockerfile

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
    ports:
      - 6379:6379